alyssa = User.create!(name: "Alyssa", username: "alyssa", password: "123456")
mike = User.create!(name: "Mike", username: "mike", password: "123456")
matt = User.create!(name: "Matt", username: "matt", password: "123456")
mo = User.create!(name: "Maurice", username: "maurice", password: "123456")
duke = User.create!(name: "Duke", username: "duke", password: "123456")