Game.create!(name: "Monopoly")
Game.create!(name: "Scrabble")
Game.create!(name: "Hanabi")
Game.create!(name: "Billionaire Banshee")
Game.create!(name: "Fluxx")
Game.create!(name: "Boggle")
Game.create!(name: "Magic")
Game.create!(name: "Risk")
Game.create!(name: "Blokus")
Game.create!(name: "Saboteur")